# MTR Matrix Configuration

# Duration in seconds for custom (user-added) MTR tasks
custom_duration_secs = 60

# Tracer startup wait in milliseconds
tracer_startup_wait_ms = 400

# HTTP listen host and port
listen_host = "0.0.0.0"
listen_port = 10000

# Source endpoints - MTR will be sent FROM these IPs
[[sources]]
name = "d-ixfirst"
ip = "44.30.18.1"

[[sources]]
name = "d-twds"
ip = "44.30.18.2"

[[sources]]
name = "ixp-stuix"
ip = "44.30.18.3"

[[sources]]
name = "ixp-tpix"
ip = "44.30.18.4"

[[sources]]
name = "mgmt-pch"
ip = "44.30.18.5"

[[sources]]
name = "mgmt_junos"
ip = "44.30.18.6"

[[sources]]
name = "u-akari"
ip = "44.30.18.7"

[[sources]]
name = "u-akw-fox"
ip = "44.30.18.8"

[[sources]]
name = "u-akw-retn"
ip = "44.30.18.9"

[[sources]]
name = "u-cogent174"
ip = "44.30.18.10"

[[sources]]
name = "u-he"
ip = "44.30.18.11"

[[sources]]
name = "u-sky"
ip = "44.30.18.12"

# Shared destinations - MTR runs continuously to these (sorted)
[[destinations]]
host = "1.1.1.1"

[[destinations]]
host = "8.8.8.8"

[[destinations]]
host = "9.9.9.9"

[[destinations]]
host = "101.101.101.101"

[[destinations]]
host = "raw.githubusercontent.com"

[[destinations]]
host = "www.apple.com"

[[destinations]]
host = "www.cloudflare.com"

[[destinations]]
host = "www.facebook.com"

[[destinations]]
host = "www.gamer.com.tw"

[[destinations]]
host = "www.github.com"

[[destinations]]
host = "www.google.com"

[[destinations]]
host = "www.hinet.net"

[[destinations]]
host = "www.microsoft.com"

[[destinations]]
host = "www.twitter.com"

[[destinations]]
host = "www.youtube.com"
